version: '3.3'

services:

  traefik:    
    image: traefik:v2.6
    ports:      
      - 80:80     
      - 443:443
    deploy:
      placement:
        constraints:         
          - node.role == manager
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:        
        - traefik.enable=true        
        - traefik.docker.network=traefik-public        
        - traefik.constraint-label=traefik-public        
        - traefik.http.middlewares.admin-auth.basicauth.users=admined:${HASHED_PASSWORD?Variable not set}

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.joinexsql.ml`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik.joinexsql.ml`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true        
        
        - traefik.http.routers.traefik-public-https.service=api@internal        
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
       
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock:ro      
      - ./certificates/acme.json:/certificates/acme.json
    command:      
      - --providers.docker      
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)     
      - --providers.docker.exposedbydefault=false      
      - --providers.docker.swarmMode      

      - --entrypoints.http.address=:80      
      - --entrypoints.https.address=:443     

      - --certificatesresolvers.le.acme.email=contato@joinex.vejartes.com.br      
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json      
      - --certificatesresolvers.le.acme.tlschallenge=true
            
      - --accesslog     
      - --log      
      - --api
    networks:      
      - traefik-public

networks:  
  traefik-public:
    external: true