version: '3.1'

services:

  db-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 152463Ed2022
    volumes:
      - ./db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    networks:
      - db-backend  

networks:
  db-backend:
    external: true
    